"""adiciona solicitacao de transferencia

Revision ID: 0b10ab0d7537
Revises: ebd7c122d159
Create Date: 2026-08-15 08:36:29.199861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b10ab0d7537'
down_revision: Union[str, Sequence[str], None] = 'ebd7c122d159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABELAS_RLS = [("solicitacao_transferencia", "isolamento_tenant_solicitacao_transferencia")]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacao_transferencia',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('aluno_id', sa.Uuid(), nullable=False),
    sa.Column('matricula_id', sa.Uuid(), nullable=False),
    sa.Column('solicitado_por_usuario_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_destino_id', sa.Uuid(), nullable=False),
    sa.Column('nif_destino', sa.String(length=50), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes_decisao', sa.Text(), nullable=True),
    sa.Column('aluno_novo_id', sa.Uuid(), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('data_decisao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matricula_id'], ['matricula.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solicitado_por_usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_destino_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # (o "drop_index ix_notificacao_usuario_lida_data" que o autogenerate
    # detetou aqui é um falso positivo, tal como nas migrações
    # anteriores — esse índice continua a ser necessário.)

    for tabela, policy in TABELAS_RLS:
        op.execute(f"ALTER TABLE {tabela} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY {policy} ON {tabela}
            USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for tabela, policy in reversed(TABELAS_RLS):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {tabela};")
        op.execute(f"ALTER TABLE {tabela} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacao_transferencia')
    # ### end Alembic commands ###
