"""site_publico_slug_e_redes_sociais

Revision ID: 13abfd659f2b
Revises: 5a8ddca790a4
Create Date: 2026-08-30 10:46:23.560491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13abfd659f2b'
down_revision: Union[str, Sequence[str], None] = '5a8ddca790a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('site_publico_slug', sa.String(length=80), nullable=True))
    op.add_column('tenant', sa.Column('site_publico_facebook', sa.String(length=255), nullable=True))
    op.add_column('tenant', sa.Column('site_publico_instagram', sa.String(length=255), nullable=True))
    op.add_column('tenant', sa.Column('site_publico_whatsapp', sa.String(length=30), nullable=True))
    op.create_unique_constraint('uq_tenant_site_publico_slug', 'tenant', ['site_publico_slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_site_publico_slug', 'tenant', type_='unique')
    op.drop_column('tenant', 'site_publico_whatsapp')
    op.drop_column('tenant', 'site_publico_instagram')
    op.drop_column('tenant', 'site_publico_facebook')
    op.drop_column('tenant', 'site_publico_slug')
    # ### end Alembic commands ###
