"""tenant_taxa_matricula_contrato_taxa_matricula

Revision ID: 37d6a0461a18
Revises: b1f06a0fdf62
Create Date: 2026-08-30 17:43:11.491979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37d6a0461a18'
down_revision: Union[str, Sequence[str], None] = 'b1f06a0fdf62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Valor padrão da taxa de matrícula da escola (Tenant.valor_taxa_matricula)
    # — usado por Financeiro (assinatura manual do contrato) e pela
    # conversão automática RN01 (candidatura self-service). Não há coluna
    # nova em fatura_mensalidade: a taxa em si é gravada como a parcela
    # nº 0 do contrato, reaproveitando a tabela existente sem migração —
    # ver app/cruds/financeiro.py::criar_contrato.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('valor_taxa_matricula', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'valor_taxa_matricula')
    # ### end Alembic commands ###
