"""audit_log_trilha_geral

Revision ID: 58f61ce25fd0
Revises: 89c421d35f1f
Create Date: 2026-08-29 23:48:40.649370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58f61ce25fd0'
down_revision: Union[str, Sequence[str], None] = '89c421d35f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Mesma convenção RLS do resto do schema (ver 8da394d41364_tabelas_iniciais_e_rls.py).
# tenant_id é nullable aqui (ações verdadeiramente públicas/sem tenant
# conhecido) — a policy exclui essas linhas de qualquer sessão
# app_tenant automaticamente (NULL = X nunca é verdadeiro em SQL), o
# que é o comportamento desejado: só o Super Admin (bypassrls) as vê.
TABELAS_RLS = [("audit_log", "isolamento_tenant_audit_log")]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('autor_id', sa.Uuid(), nullable=True),
    sa.Column('autor_perfil', sa.String(length=50), nullable=True),
    sa.Column('acao', sa.String(length=10), nullable=False),
    sa.Column('entidade', sa.String(length=80), nullable=False),
    sa.Column('entidade_id', sa.String(length=64), nullable=False),
    sa.Column('alteracoes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_autor', 'audit_log', ['autor_id'], unique=False)
    op.create_index('ix_audit_log_entidade', 'audit_log', ['entidade', 'entidade_id'], unique=False)
    op.create_index('ix_audit_log_tenant_criado_em', 'audit_log', ['tenant_id', 'criado_em'], unique=False)
    # ### end Alembic commands ###

    for tabela, policy in TABELAS_RLS:
        op.execute(f"ALTER TABLE {tabela} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY {policy} ON {tabela}
            USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for tabela, policy in reversed(TABELAS_RLS):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {tabela};")
        op.execute(f"ALTER TABLE {tabela} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_log_tenant_criado_em', table_name='audit_log')
    op.drop_index('ix_audit_log_entidade', table_name='audit_log')
    op.drop_index('ix_audit_log_autor', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
