"""site_publico_por_escola

Revision ID: 5a8ddca790a4
Revises: bb1d120de1c5
Create Date: 2026-08-30 01:37:37.929415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8ddca790a4'
down_revision: Union[str, Sequence[str], None] = 'bb1d120de1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Mesma convenção RLS do resto do schema.
TABELAS_RLS = [("site_publico_foto", "isolamento_tenant_site_publico_foto")]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_publico_foto',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('chave_storage', sa.String(length=500), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_publico_foto_tenant_id'), 'site_publico_foto', ['tenant_id'], unique=False)
    op.add_column('tenant', sa.Column('site_publico_ativo', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tenant', sa.Column('site_publico_missao', sa.Text(), nullable=True))
    op.add_column('tenant', sa.Column('site_publico_metodologia', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    for tabela, policy in TABELAS_RLS:
        op.execute(f"ALTER TABLE {tabela} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY {policy} ON {tabela}
            USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for tabela, policy in reversed(TABELAS_RLS):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {tabela};")
        op.execute(f"ALTER TABLE {tabela} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'site_publico_metodologia')
    op.drop_column('tenant', 'site_publico_missao')
    op.drop_column('tenant', 'site_publico_ativo')
    op.drop_index(op.f('ix_site_publico_foto_tenant_id'), table_name='site_publico_foto')
    op.drop_table('site_publico_foto')
    # ### end Alembic commands ###
