"""adiciona lead_candidato, funil_etapa e oportunidade_crm

Revision ID: 66e402cbacff
Revises: 56f74f1301bb
Create Date: 2026-08-13 01:15:28.227123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e402cbacff'
down_revision: Union[str, Sequence[str], None] = '56f74f1301bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABELAS_RLS = [
    ("funil_etapa", "isolamento_tenant_funil_etapa"),
    ("lead_candidato", "isolamento_tenant_lead_candidato"),
    ("oportunidade_crm", "isolamento_tenant_oportunidade_crm"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funil_etapa',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('nome_etapa', sa.String(length=100), nullable=False),
    sa.Column('eh_etapa_ganho', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'ordem', name='uq_funil_etapa_tenant_ordem')
    )
    op.create_table('lead_candidato',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('curso_interesse_id', sa.Uuid(), nullable=True),
    sa.Column('nome_responsavel', sa.String(length=255), nullable=False),
    sa.Column('email_contato', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('nome_aluno_candidato', sa.String(length=255), nullable=False),
    sa.Column('data_nascimento_candidato', sa.Date(), nullable=True),
    sa.Column('origem_lead', sa.String(length=30), nullable=False),
    sa.Column('data_entrada', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['curso_interesse_id'], ['curso.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oportunidade_crm',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('etapa_id', sa.Uuid(), nullable=False),
    sa.Column('valor_estimado_anual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_fecho_prevista', sa.Date(), nullable=True),
    sa.Column('aluno_gerado_id', sa.Uuid(), nullable=True),
    sa.Column('responsavel_gerado_id', sa.Uuid(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_gerado_id'], ['aluno.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['etapa_id'], ['funil_etapa.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['lead_candidato.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsavel_gerado_id'], ['responsavel_financeiro_legal.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    for tabela, policy in TABELAS_RLS:
        op.execute(f"ALTER TABLE {tabela} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY {policy} ON {tabela}
            USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for tabela, policy in reversed(TABELAS_RLS):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {tabela};")
        op.execute(f"ALTER TABLE {tabela} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oportunidade_crm')
    op.drop_table('lead_candidato')
    op.drop_table('funil_etapa')
    # ### end Alembic commands ###
