"""mensagem_lead

Revision ID: 78c0cfec3bd1
Revises: aeb36dfdba6f
Create Date: 2026-09-07 08:48:20.405705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c0cfec3bd1'
down_revision: Union[str, Sequence[str], None] = 'aeb36dfdba6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Mesmo padrão de RLS de sempre — mensagem_lead é uma child table de
# lead_candidato, tal como resposta_comunicado é de comunicado.
TABELAS_RLS = [("mensagem_lead", "mensagem_lead_tenant_isolation")]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagem_lead',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('autor_tipo', sa.String(length=10), nullable=False),
    sa.Column('autor_nome', sa.String(length=255), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead_candidato.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagem_lead_lead_id'), 'mensagem_lead', ['lead_id'], unique=False)
    op.create_index(op.f('ix_mensagem_lead_tenant_id'), 'mensagem_lead', ['tenant_id'], unique=False)
    op.add_column('lead_candidato', sa.Column('mensagem', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    for tabela, policy in TABELAS_RLS:
        op.execute(f"ALTER TABLE {tabela} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY {policy} ON {tabela}
            USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for tabela, policy in reversed(TABELAS_RLS):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {tabela};")
        op.execute(f"ALTER TABLE {tabela} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_candidato', 'mensagem')
    op.drop_index(op.f('ix_mensagem_lead_tenant_id'), table_name='mensagem_lead')
    op.drop_index(op.f('ix_mensagem_lead_lead_id'), table_name='mensagem_lead')
    op.drop_table('mensagem_lead')
    # ### end Alembic commands ###
