"""adiciona contrato_financeiro e fatura_mensalidade

Revision ID: 8c59c8ffa689
Revises: 4bb16f8e6da2
Create Date: 2026-08-12 01:21:07.613264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c59c8ffa689'
down_revision: Union[str, Sequence[str], None] = '4bb16f8e6da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TABELAS_RLS = [
    ("contrato_financeiro", "isolamento_tenant_contrato_financeiro"),
    ("fatura_mensalidade", "isolamento_tenant_fatura_mensalidade"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato_financeiro',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('matricula_id', sa.Uuid(), nullable=False),
    sa.Column('responsavel_id', sa.Uuid(), nullable=False),
    sa.Column('valor_total_anual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_parcelas', sa.Integer(), nullable=False),
    sa.Column('dia_vencimento_padrao', sa.Integer(), nullable=False),
    sa.Column('percentual_desconto_bolsa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['matricula_id'], ['matricula.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsavel_financeiro_legal.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula_id', name='uq_contrato_financeiro_matricula')
    )
    op.create_table('fatura_mensalidade',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('contrato_id', sa.Uuid(), nullable=False),
    sa.Column('numero_parcela', sa.Integer(), nullable=False),
    sa.Column('valor_original', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('status_pagamento', sa.String(length=20), nullable=False),
    sa.Column('data_pagamento_realizado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valor_pago_realizado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=30), nullable=True),
    sa.Column('lembrete_previo_enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lembrete_vencimento_enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aviso_atraso_enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato_financeiro.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_id', 'numero_parcela', name='uq_fatura_contrato_parcela')
    )
    # ### end Alembic commands ###

    for tabela, policy in TABELAS_RLS:
        op.execute(f"ALTER TABLE {tabela} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY {policy} ON {tabela}
            USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for tabela, policy in reversed(TABELAS_RLS):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {tabela};")
        op.execute(f"ALTER TABLE {tabela} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fatura_mensalidade')
    op.drop_table('contrato_financeiro')
    # ### end Alembic commands ###
