"""modelos_site_publico_e_curso_programatico

Revision ID: 920664459636
Revises: 13abfd659f2b
Create Date: 2026-08-30 11:37:31.793743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920664459636'
down_revision: Union[str, Sequence[str], None] = '13abfd659f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curso', sa.Column('site_publico_visivel', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('curso', sa.Column('site_publico_descricao', sa.Text(), nullable=True))
    op.add_column('tenant', sa.Column('site_publico_template', sa.String(length=30), server_default='classico', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'site_publico_template')
    op.drop_column('curso', 'site_publico_descricao')
    op.drop_column('curso', 'site_publico_visivel')
    # ### end Alembic commands ###
