"""pedido_rematricula

Revision ID: a7d5bdefb1f8
Revises: 37d6a0461a18
Create Date: 2026-08-30 18:29:02.984758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d5bdefb1f8'
down_revision: Union[str, Sequence[str], None] = '37d6a0461a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Mesma convenção RLS do resto do schema.
TABELAS_RLS = [("pedido_rematricula", "isolamento_tenant_pedido_rematricula")]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido_rematricula',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('aluno_id', sa.Uuid(), nullable=False),
    sa.Column('matricula_atual_id', sa.Uuid(), nullable=False),
    sa.Column('ano_letivo_destino', sa.Integer(), nullable=False),
    sa.Column('solicitado_por_usuario_id', sa.Uuid(), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matricula_atual_id'], ['matricula.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solicitado_por_usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'ano_letivo_destino', name='uq_pedido_rematricula_aluno_ano')
    )
    op.create_index(op.f('ix_pedido_rematricula_tenant_id'), 'pedido_rematricula', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    for tabela, policy in TABELAS_RLS:
        op.execute(f"ALTER TABLE {tabela} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY {policy} ON {tabela}
            USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for tabela, policy in reversed(TABELAS_RLS):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {tabela};")
        op.execute(f"ALTER TABLE {tabela} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_rematricula_tenant_id'), table_name='pedido_rematricula')
    op.drop_table('pedido_rematricula')
    # ### end Alembic commands ###
