"""resposta_comunicado

Revision ID: aeb36dfdba6f
Revises: f0c965f676ff
Create Date: 2026-09-07 08:22:26.253153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb36dfdba6f'
down_revision: Union[str, Sequence[str], None] = 'f0c965f676ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Mesmo padrão de RLS de todas as outras tabelas por tenant desta app —
# ver bb1d120de1c5_sistema_de_tickets_suporte.py (a tabela irmã mais
# próxima, mesma forma de child-de-uma-entidade-pai).
TABELAS_RLS = [("resposta_comunicado", "resposta_comunicado_tenant_isolation")]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resposta_comunicado',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('comunicado_id', sa.Uuid(), nullable=False),
    sa.Column('aluno_id', sa.Uuid(), nullable=False),
    sa.Column('autor_usuario_id', sa.Uuid(), nullable=True),
    sa.Column('autor_nome', sa.String(length=255), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['autor_usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['comunicado_id'], ['comunicado.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resposta_comunicado_comunicado_id'), 'resposta_comunicado', ['comunicado_id'], unique=False)
    op.create_index(op.f('ix_resposta_comunicado_tenant_id'), 'resposta_comunicado', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    for tabela, policy in TABELAS_RLS:
        op.execute(f"ALTER TABLE {tabela} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY {policy} ON {tabela}
            USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for tabela, policy in reversed(TABELAS_RLS):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {tabela};")
        op.execute(f"ALTER TABLE {tabela} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resposta_comunicado_tenant_id'), table_name='resposta_comunicado')
    op.drop_index(op.f('ix_resposta_comunicado_comunicado_id'), table_name='resposta_comunicado')
    op.drop_table('resposta_comunicado')
    # ### end Alembic commands ###
