"""fim_de_ciclo_reingresso_documentos_matricula

Revision ID: b1f06a0fdf62
Revises: b5d9f0cb9c5f
Create Date: 2026-08-30 16:14:46.961000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f06a0fdf62'
down_revision: Union[str, Sequence[str], None] = 'b5d9f0cb9c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Mesma convenção RLS do resto do schema.
TABELAS_RLS = [("matricula_documento", "isolamento_tenant_matricula_documento")]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matricula_documento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('matricula_id', sa.Uuid(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('chave_storage', sa.String(length=500), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['matricula_id'], ['matricula.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matricula_documento_matricula_id'), 'matricula_documento', ['matricula_id'], unique=False)
    op.create_index(op.f('ix_matricula_documento_tenant_id'), 'matricula_documento', ['tenant_id'], unique=False)
    op.add_column('matricula', sa.Column('motivo', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    for tabela, policy in TABELAS_RLS:
        op.execute(f"ALTER TABLE {tabela} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY {policy} ON {tabela}
            USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for tabela, policy in reversed(TABELAS_RLS):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {tabela};")
        op.execute(f"ALTER TABLE {tabela} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matricula', 'motivo')
    op.drop_index(op.f('ix_matricula_documento_tenant_id'), table_name='matricula_documento')
    op.drop_index(op.f('ix_matricula_documento_matricula_id'), table_name='matricula_documento')
    op.drop_table('matricula_documento')
    # ### end Alembic commands ###
