"""matricula_self_service_documentos_candidatura

Revision ID: b5d9f0cb9c5f
Revises: 920664459636
Create Date: 2026-08-30 14:16:59.687580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d9f0cb9c5f'
down_revision: Union[str, Sequence[str], None] = '920664459636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Mesma convenção RLS do resto do schema (ver 66e402cbacff, que fez o
# mesmo para lead_candidato/oportunidade_crm).
TABELAS_RLS = [("lead_documento", "isolamento_tenant_lead_documento")]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_documento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('chave_storage', sa.String(length=500), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead_candidato.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_documento_lead_id'), 'lead_documento', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_documento_tenant_id'), 'lead_documento', ['tenant_id'], unique=False)
    op.add_column('lead_candidato', sa.Column('aceitou_regulamento', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###

    for tabela, policy in TABELAS_RLS:
        op.execute(f"ALTER TABLE {tabela} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY {policy} ON {tabela}
            USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for tabela, policy in reversed(TABELAS_RLS):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {tabela};")
        op.execute(f"ALTER TABLE {tabela} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_candidato', 'aceitou_regulamento')
    op.drop_index(op.f('ix_lead_documento_tenant_id'), table_name='lead_documento')
    op.drop_index(op.f('ix_lead_documento_lead_id'), table_name='lead_documento')
    op.drop_table('lead_documento')
    # ### end Alembic commands ###
