"""sistema_de_tickets_suporte

Revision ID: bb1d120de1c5
Revises: 58f61ce25fd0
Create Date: 2026-08-30 01:03:11.319303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1d120de1c5'
down_revision: Union[str, Sequence[str], None] = '58f61ce25fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Mesma convenção RLS do resto do schema (ver 8da394d41364_tabelas_iniciais_e_rls.py
# e 58f61ce25fd0_audit_log_trilha_geral.py). tenant_id nullable nas duas
# tabelas — um ticket de um visitante sem conta fica invisível a
# qualquer sessão app_tenant (NULL = X nunca é verdadeiro em SQL), só o
# Super Admin (bypassrls) o vê, que é o comportamento pretendido.
TABELAS_RLS = [
    ("ticket_suporte", "isolamento_tenant_ticket_suporte"),
    ("ticket_mensagem", "isolamento_tenant_ticket_mensagem"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_suporte',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('autor_nome', sa.String(length=255), nullable=False),
    sa.Column('autor_email', sa.String(length=255), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='ABERTO', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_suporte_estado_criado_em', 'ticket_suporte', ['estado', 'criado_em'], unique=False)
    op.create_index('ix_ticket_suporte_tenant_estado', 'ticket_suporte', ['tenant_id', 'estado'], unique=False)
    op.create_table('ticket_mensagem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('autor_tipo', sa.String(length=10), nullable=False),
    sa.Column('autor_nome', sa.String(length=255), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket_suporte.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_mensagem_ticket_id', 'ticket_mensagem', ['ticket_id'], unique=False)
    # ### end Alembic commands ###

    for tabela, policy in TABELAS_RLS:
        op.execute(f"ALTER TABLE {tabela} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY {policy} ON {tabela}
            USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for tabela, policy in reversed(TABELAS_RLS):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {tabela};")
        op.execute(f"ALTER TABLE {tabela} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_mensagem_ticket_id', table_name='ticket_mensagem')
    op.drop_table('ticket_mensagem')
    op.drop_index('ix_ticket_suporte_tenant_estado', table_name='ticket_suporte')
    op.drop_index('ix_ticket_suporte_estado_criado_em', table_name='ticket_suporte')
    op.drop_table('ticket_suporte')
    # ### end Alembic commands ###
