"""indices_escala_fase6

Revision ID: cde309e6fb09
Revises: 184aa58ca724
Create Date: 2026-08-28 16:27:12.070319

Fase 6 — escala: nenhuma das colunas tenant_id em todo o esquema (51,
antes desta migração) tinha índice — e TODA a query desta app filtra
por tenant_id, seja explicitamente no crud ou implicitamente via a
policy de RLS (`USING (tenant_id = current_setting(...))`). Sem
índice, isso é sequential scan garantido em cada pedido, em qualquer
tabela, assim que deixar de caber inteira em cache — com milhares de
escolas, não é uma questão de "se", é de "quando". Esta migração
acrescenta um índice simples em tenant_id a todas elas.

Duas compostas a mais, para as duas queries mais pesadas da app:
ix_fatura_tenant_status (fatura_mensalidade) cobre a régua de cobrança
diária (RN04), que varre TODAS as faturas PENDENTE de TODAS as escolas
ATIVAS todos os dias; ix_matricula_tenant_status (matricula) cobre
"matrículas ativas", a consulta mais comum sobre essa tabela
(transferências, boletim, financeiro, portal).

Também declara formalmente ix_notificacao_usuario_lida_data (já
existia desde a migração original 48640d281d79, mas nunca tinha sido
posto em __table_args__ — por isso aparecia como "drift" no
autogenerate de toda migração desde então, sem que nenhuma alguma vez
o removesse de facto). Resultado: não aparece mais nesta nem nas
próximas migrações.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde309e6fb09'
down_revision: Union[str, Sequence[str], None] = '184aa58ca724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_aluno_tenant_id'), 'aluno', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_aluno_responsavel_tenant_id'), 'aluno_responsavel', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_anexo_comunicacao_tenant_id'), 'anexo_comunicacao', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_assinatura_tenant_tenant_id'), 'assinatura_tenant', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_avaliacao_tenant_id'), 'avaliacao', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_comunicado_tenant_id'), 'comunicado', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_contrato_financeiro_tenant_id'), 'contrato_financeiro', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_curso_tenant_id'), 'curso', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_disciplina_tenant_id'), 'disciplina', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_fatura_mensalidade_tenant_id'), 'fatura_mensalidade', ['tenant_id'], unique=False)
    op.create_index('ix_fatura_tenant_status', 'fatura_mensalidade', ['tenant_id', 'status_pagamento'], unique=False)
    op.create_index(op.f('ix_funil_etapa_tenant_id'), 'funil_etapa', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_grade_curricular_tenant_id'), 'grade_curricular', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_horario_aula_tenant_id'), 'horario_aula', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_lead_candidato_tenant_id'), 'lead_candidato', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_lms_exame_tenant_id'), 'lms_exame', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_lms_exame_questao_tenant_id'), 'lms_exame_questao', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_lms_questao_tenant_id'), 'lms_questao', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_lms_tentativa_exame_tenant_id'), 'lms_tentativa_exame', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_login_historico_tenant_id'), 'login_historico', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_material_aula_tenant_id'), 'material_aula', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_matricula_tenant_id'), 'matricula', ['tenant_id'], unique=False)
    op.create_index('ix_matricula_tenant_status', 'matricula', ['tenant_id', 'status_matricula'], unique=False)
    op.create_index(op.f('ix_nota_avaliacao_tenant_id'), 'nota_avaliacao', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notificacao_tenant_id'), 'notificacao', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_objetivo_aprendizagem_tenant_id'), 'objetivo_aprendizagem', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_oportunidade_crm_tenant_id'), 'oportunidade_crm', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_password_reset_token_tenant_id'), 'password_reset_token', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_periodo_avaliacao_tenant_id'), 'periodo_avaliacao', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_preco_documento_tenant_id'), 'preco_documento', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_professor_tenant_id'), 'professor', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_professor_turma_disciplina_tenant_id'), 'professor_turma_disciplina', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_propina_serie_tenant_id'), 'propina_serie', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_recibo_tenant_id'), 'recibo', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_tenant_id'), 'refresh_token', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_registro_frequencia_tenant_id'), 'registro_frequencia', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_registro_nota_tenant_id'), 'registro_nota', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_registro_nota_auditoria_tenant_id'), 'registro_nota_auditoria', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_responsavel_financeiro_legal_tenant_id'), 'responsavel_financeiro_legal', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_serie_ano_tenant_id'), 'serie_ano', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_solicitacao_documento_emissao_tenant_id'), 'solicitacao_documento_emissao', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_solicitacao_documento_escola_tenant_id'), 'solicitacao_documento_escola', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_solicitacao_transferencia_tenant_id'), 'solicitacao_transferencia', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tarefa_tenant_id'), 'tarefa', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tarefa_avaliacao_tenant_id'), 'tarefa_avaliacao', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_template_documento_personalizado_tenant_id'), 'template_documento_personalizado', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tipo_avaliacao_config_tenant_id'), 'tipo_avaliacao_config', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_transacao_gateway_tenant_id'), 'transacao_gateway', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_trilha_recuperacao_tenant_id'), 'trilha_recuperacao', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_turma_tenant_id'), 'turma', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_usuario_tenant_id'), 'usuario', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_usuario_auditoria_tenant_id'), 'usuario_auditoria', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_auditoria_tenant_id'), table_name='usuario_auditoria')
    op.drop_index(op.f('ix_usuario_tenant_id'), table_name='usuario')
    op.drop_index(op.f('ix_turma_tenant_id'), table_name='turma')
    op.drop_index(op.f('ix_trilha_recuperacao_tenant_id'), table_name='trilha_recuperacao')
    op.drop_index(op.f('ix_transacao_gateway_tenant_id'), table_name='transacao_gateway')
    op.drop_index(op.f('ix_tipo_avaliacao_config_tenant_id'), table_name='tipo_avaliacao_config')
    op.drop_index(op.f('ix_template_documento_personalizado_tenant_id'), table_name='template_documento_personalizado')
    op.drop_index(op.f('ix_tarefa_avaliacao_tenant_id'), table_name='tarefa_avaliacao')
    op.drop_index(op.f('ix_tarefa_tenant_id'), table_name='tarefa')
    op.drop_index(op.f('ix_solicitacao_transferencia_tenant_id'), table_name='solicitacao_transferencia')
    op.drop_index(op.f('ix_solicitacao_documento_escola_tenant_id'), table_name='solicitacao_documento_escola')
    op.drop_index(op.f('ix_solicitacao_documento_emissao_tenant_id'), table_name='solicitacao_documento_emissao')
    op.drop_index(op.f('ix_serie_ano_tenant_id'), table_name='serie_ano')
    op.drop_index(op.f('ix_responsavel_financeiro_legal_tenant_id'), table_name='responsavel_financeiro_legal')
    op.drop_index(op.f('ix_registro_nota_auditoria_tenant_id'), table_name='registro_nota_auditoria')
    op.drop_index(op.f('ix_registro_nota_tenant_id'), table_name='registro_nota')
    op.drop_index(op.f('ix_registro_frequencia_tenant_id'), table_name='registro_frequencia')
    op.drop_index(op.f('ix_refresh_token_tenant_id'), table_name='refresh_token')
    op.drop_index(op.f('ix_recibo_tenant_id'), table_name='recibo')
    op.drop_index(op.f('ix_propina_serie_tenant_id'), table_name='propina_serie')
    op.drop_index(op.f('ix_professor_turma_disciplina_tenant_id'), table_name='professor_turma_disciplina')
    op.drop_index(op.f('ix_professor_tenant_id'), table_name='professor')
    op.drop_index(op.f('ix_preco_documento_tenant_id'), table_name='preco_documento')
    op.drop_index(op.f('ix_periodo_avaliacao_tenant_id'), table_name='periodo_avaliacao')
    op.drop_index(op.f('ix_password_reset_token_tenant_id'), table_name='password_reset_token')
    op.drop_index(op.f('ix_oportunidade_crm_tenant_id'), table_name='oportunidade_crm')
    op.drop_index(op.f('ix_objetivo_aprendizagem_tenant_id'), table_name='objetivo_aprendizagem')
    op.drop_index(op.f('ix_notificacao_tenant_id'), table_name='notificacao')
    op.drop_index(op.f('ix_nota_avaliacao_tenant_id'), table_name='nota_avaliacao')
    op.drop_index('ix_matricula_tenant_status', table_name='matricula')
    op.drop_index(op.f('ix_matricula_tenant_id'), table_name='matricula')
    op.drop_index(op.f('ix_material_aula_tenant_id'), table_name='material_aula')
    op.drop_index(op.f('ix_login_historico_tenant_id'), table_name='login_historico')
    op.drop_index(op.f('ix_lms_tentativa_exame_tenant_id'), table_name='lms_tentativa_exame')
    op.drop_index(op.f('ix_lms_questao_tenant_id'), table_name='lms_questao')
    op.drop_index(op.f('ix_lms_exame_questao_tenant_id'), table_name='lms_exame_questao')
    op.drop_index(op.f('ix_lms_exame_tenant_id'), table_name='lms_exame')
    op.drop_index(op.f('ix_lead_candidato_tenant_id'), table_name='lead_candidato')
    op.drop_index(op.f('ix_horario_aula_tenant_id'), table_name='horario_aula')
    op.drop_index(op.f('ix_grade_curricular_tenant_id'), table_name='grade_curricular')
    op.drop_index(op.f('ix_funil_etapa_tenant_id'), table_name='funil_etapa')
    op.drop_index('ix_fatura_tenant_status', table_name='fatura_mensalidade')
    op.drop_index(op.f('ix_fatura_mensalidade_tenant_id'), table_name='fatura_mensalidade')
    op.drop_index(op.f('ix_disciplina_tenant_id'), table_name='disciplina')
    op.drop_index(op.f('ix_curso_tenant_id'), table_name='curso')
    op.drop_index(op.f('ix_contrato_financeiro_tenant_id'), table_name='contrato_financeiro')
    op.drop_index(op.f('ix_comunicado_tenant_id'), table_name='comunicado')
    op.drop_index(op.f('ix_avaliacao_tenant_id'), table_name='avaliacao')
    op.drop_index(op.f('ix_assinatura_tenant_tenant_id'), table_name='assinatura_tenant')
    op.drop_index(op.f('ix_anexo_comunicacao_tenant_id'), table_name='anexo_comunicacao')
    op.drop_index(op.f('ix_aluno_responsavel_tenant_id'), table_name='aluno_responsavel')
    op.drop_index(op.f('ix_aluno_tenant_id'), table_name='aluno')
    # ### end Alembic commands ###
