"""avaliacoes agendadas: TipoAvaliacaoConfig, campos Avaliacao, nota minima Tenant

Revision ID: cfe1a4e36025
Revises: adbbbd7e0d74
Create Date: 2026-08-16 19:19:55.243305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe1a4e36025'
down_revision: Union[str, Sequence[str], None] = 'adbbbd7e0d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# RLS: mesma lista/padrão usado em todas as migrações anteriores desde
# a introdução de multi-tenancy — isolamento_tenant_<tabela> em cada
# tabela nova com tenant_id.
TABELAS_RLS = ["tipo_avaliacao_config"]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_avaliacao_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('requer_agendamento', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nome', name='uq_tipo_avaliacao_tenant_nome')
    )
    op.add_column('avaliacao', sa.Column('hora_inicio', sa.Time(), nullable=True))
    op.add_column('avaliacao', sa.Column('hora_fim', sa.Time(), nullable=True))
    op.add_column('avaliacao', sa.Column('sala', sa.String(length=50), nullable=True))
    op.add_column('avaliacao', sa.Column('data_limite_correcao', sa.Date(), nullable=True))
    op.add_column('avaliacao', sa.Column('grupo_agendamento_id', sa.Uuid(), nullable=True))
    op.alter_column('avaliacao', 'tipo_avaliacao',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ix_notificacao_usuario_lida_data: drift pré-existente e não
    # relacionado (mesma nota das migrações anteriores) — omitido de
    # propósito, não apagar o índice.
    op.add_column('tenant', sa.Column('nota_minima_aprovacao', sa.Numeric(precision=4, scale=2), nullable=True))
    # ### end Alembic commands ###

    for tabela in TABELAS_RLS:
        op.execute(f"ALTER TABLE {tabela} ENABLE ROW LEVEL SECURITY")
        op.execute(f"""
            CREATE POLICY isolamento_tenant_{tabela} ON {tabela}
            USING (tenant_id = current_setting('app.tenant_id')::uuid)
        """)

    # Seed: cada tenant existente recebe os dois tipos que já eram
    # implícitos no código (CONTINUA/PROVA) — os nomes têm de bater
    # certo com o que já está gravado em avaliacao.tipo_avaliacao para
    # não quebrar avaliações já criadas. Só PROVA exige agendamento
    # (mantém o comportamento de hoje: só provas formais precisam de
    # data/hora/sala marcadas pela Secretaria).
    op.execute("""
        INSERT INTO tipo_avaliacao_config (id, tenant_id, nome, requer_agendamento, ativo)
        SELECT gen_random_uuid(), id, 'CONTINUA', false, true FROM tenant
    """)
    op.execute("""
        INSERT INTO tipo_avaliacao_config (id, tenant_id, nome, requer_agendamento, ativo)
        SELECT gen_random_uuid(), id, 'PROVA', true, true FROM tenant
    """)


def downgrade() -> None:
    """Downgrade schema."""
    for tabela in TABELAS_RLS:
        op.execute(f"DROP POLICY IF EXISTS isolamento_tenant_{tabela} ON {tabela}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'nota_minima_aprovacao')
    op.alter_column('avaliacao', 'tipo_avaliacao',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('avaliacao', 'grupo_agendamento_id')
    op.drop_column('avaliacao', 'data_limite_correcao')
    op.drop_column('avaliacao', 'sala')
    op.drop_column('avaliacao', 'hora_fim')
    op.drop_column('avaliacao', 'hora_inicio')
    op.drop_table('tipo_avaliacao_config')
    # ### end Alembic commands ###
