"""adiciona solicitacoes de documentos

Revision ID: ebd7c122d159
Revises: 48640d281d79
Create Date: 2026-08-15 01:26:05.905076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebd7c122d159'
down_revision: Union[str, Sequence[str], None] = '48640d281d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABELAS_RLS = [
    ("preco_documento", "isolamento_tenant_preco_documento"),
    ("solicitacao_documento_emissao", "isolamento_tenant_solicitacao_documento_emissao"),
    ("solicitacao_documento_escola", "isolamento_tenant_solicitacao_documento_escola"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preco_documento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=30), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'tipo_documento', name='uq_preco_documento_tenant_tipo')
    )
    op.create_table('solicitacao_documento_emissao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('aluno_id', sa.Uuid(), nullable=False),
    sa.Column('solicitante_usuario_id', sa.Uuid(), nullable=True),
    sa.Column('tipo_documento', sa.String(length=30), nullable=False),
    sa.Column('descricao_outro', sa.String(length=255), nullable=True),
    sa.Column('formato_entrega', sa.String(length=10), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paypal_order_id', sa.String(length=50), nullable=True),
    sa.Column('observacoes_escola', sa.Text(), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solicitante_usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao_documento_escola',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('destinatario_tipo', sa.String(length=20), nullable=False),
    sa.Column('destinatario_aluno_id', sa.Uuid(), nullable=True),
    sa.Column('destinatario_responsavel_id', sa.Uuid(), nullable=True),
    sa.Column('destinatario_professor_id', sa.Uuid(), nullable=True),
    sa.Column('solicitado_por_usuario_id', sa.Uuid(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resposta_texto', sa.Text(), nullable=True),
    sa.Column('respondido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['destinatario_aluno_id'], ['aluno.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destinatario_professor_id'], ['professor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destinatario_responsavel_id'], ['responsavel_financeiro_legal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solicitado_por_usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # (a linha "drop_index ix_notificacao_usuario_lida_data" que o
    # autogenerate detetou aqui é um falso positivo — esse índice já
    # existe desde a migração 48640d281d79 e continua a ser necessário;
    # removida manualmente desta migração.)

    for tabela, policy in TABELAS_RLS:
        op.execute(f"ALTER TABLE {tabela} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY {policy} ON {tabela}
            USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for tabela, policy in reversed(TABELAS_RLS):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {tabela};")
        op.execute(f"ALTER TABLE {tabela} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacao_documento_escola')
    op.drop_table('solicitacao_documento_emissao')
    op.drop_table('preco_documento')
    # ### end Alembic commands ###
