"""adiciona configuracoes de escola ao tenant

Revision ID: f699505ccde4
Revises: b36bab74524e
Create Date: 2026-08-15 16:48:54.817340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f699505ccde4'
down_revision: Union[str, Sequence[str], None] = 'b36bab74524e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (a linha "drop_index ix_notificacao_usuario_lida_data" que o
    # autogenerate detetou aqui é um falso positivo — esse índice já
    # existe desde a migração 48640d281d79 e continua a ser necessário;
    # removida manualmente desta migração, mesmo padrão das anteriores.)
    op.add_column('tenant', sa.Column('iban', sa.String(length=50), nullable=True))
    op.add_column('tenant', sa.Column('moeda', sa.String(length=3), server_default='EUR', nullable=False))
    op.add_column('tenant', sa.Column('telefone_contacto', sa.String(length=30), nullable=True))
    op.add_column('tenant', sa.Column('email_contacto', sa.String(length=255), nullable=True))
    op.add_column('tenant', sa.Column('morada', sa.String(length=255), nullable=True))
    op.add_column('tenant', sa.Column('cidade', sa.String(length=100), nullable=True))
    op.add_column('tenant', sa.Column('codigo_postal', sa.String(length=20), nullable=True))
    op.add_column('tenant', sa.Column('pais', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'pais')
    op.drop_column('tenant', 'codigo_postal')
    op.drop_column('tenant', 'cidade')
    op.drop_column('tenant', 'morada')
    op.drop_column('tenant', 'email_contacto')
    op.drop_column('tenant', 'telefone_contacto')
    op.drop_column('tenant', 'moeda')
    op.drop_column('tenant', 'iban')
    # ### end Alembic commands ###
