"""conta_ativacao_e_ano_letivo

Revision ID: f76cb7ec66e8
Revises: c7d2e4f9a1b3
Create Date: 2026-09-06 14:26:19.301661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76cb7ec66e8'
down_revision: Union[str, Sequence[str], None] = 'c7d2e4f9a1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Nova tabela com isolamento por tenant — mesmo padrão de RLS de
# c5114fc15f70_password_reset_token.py (a tabela irmã desta, mesma
# estrutura). Na prática só é escrita/lida pelo role app_sistema (o
# fluxo de ativação é pré-autenticado, ver cruds/auth.py), mas ganha a
# policy por consistência e defesa em profundidade, como todas as
# outras tabelas.
TABELAS_RLS = ["conta_ativacao_token"]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conta_ativacao_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_conta_ativacao_token_tenant_id'), 'conta_ativacao_token', ['tenant_id'], unique=False)
    op.add_column('tenant', sa.Column('data_inicio_ano_letivo', sa.Date(), nullable=True))
    op.add_column('tenant', sa.Column('data_fim_ano_letivo', sa.Date(), nullable=True))
    op.add_column('tenant', sa.Column('ano_letivo_atual', sa.Integer(), nullable=True))
    op.add_column('usuario', sa.Column('email_verificado', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###

    for tabela in TABELAS_RLS:
        op.execute(f"ALTER TABLE {tabela} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY isolamento_tenant_{tabela} ON {tabela}
            USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for tabela in TABELAS_RLS:
        op.execute(f"DROP POLICY IF EXISTS isolamento_tenant_{tabela} ON {tabela};")
        op.execute(f"ALTER TABLE {tabela} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'email_verificado')
    op.drop_column('tenant', 'ano_letivo_atual')
    op.drop_column('tenant', 'data_fim_ano_letivo')
    op.drop_column('tenant', 'data_inicio_ano_letivo')
    op.drop_index(op.f('ix_conta_ativacao_token_tenant_id'), table_name='conta_ativacao_token')
    op.drop_table('conta_ativacao_token')
    # ### end Alembic commands ###
