"""evento_e_evento_foto

Revision ID: f9c7d1e1d3a5
Revises: 78c0cfec3bd1
Create Date: 2026-09-07 09:10:10.615817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c7d1e1d3a5'
down_revision: Union[str, Sequence[str], None] = '78c0cfec3bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Mesmo padrão de RLS de sempre — evento (pai) + evento_foto (filho),
# ambas isoladas por tenant_id (mesma forma de 66e402cbacff, que criou
# lead_candidato + oportunidade_crm numa só migração).
TABELAS_RLS = [
    ("evento", "evento_tenant_isolation"),
    ("evento_foto", "evento_foto_tenant_isolation"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('publicado', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evento_tenant_id'), 'evento', ['tenant_id'], unique=False)
    op.create_table('evento_foto',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('evento_id', sa.Uuid(), nullable=False),
    sa.Column('chave_storage', sa.String(length=500), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evento_foto_evento_id'), 'evento_foto', ['evento_id'], unique=False)
    op.create_index(op.f('ix_evento_foto_tenant_id'), 'evento_foto', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    for tabela, policy in TABELAS_RLS:
        op.execute(f"ALTER TABLE {tabela} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY {policy} ON {tabela}
            USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    for tabela, policy in reversed(TABELAS_RLS):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {tabela};")
        op.execute(f"ALTER TABLE {tabela} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evento_foto_tenant_id'), table_name='evento_foto')
    op.drop_index(op.f('ix_evento_foto_evento_id'), table_name='evento_foto')
    op.drop_table('evento_foto')
    op.drop_index(op.f('ix_evento_tenant_id'), table_name='evento')
    op.drop_table('evento')
    # ### end Alembic commands ###
